# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='botDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('firstLocation', models.CharField(max_length=100)),
                ('secondLocation', models.CharField(max_length=100)),
                ('firstDate', models.CharField(max_length=100)),
                ('secondDate', models.CharField(max_length=100)),
            ],
        ),
    ]
